export type PaymentBlessingLanguage = 'zh' | 'en'

export const PAYMENT_BLESSINGS: Record<PaymentBlessingLanguage, readonly string[]> = {
  zh: [
    '愿你眼里有光，心中有梦，脚下的每一步都走向喜欢的生活。',
    '愿所有认真生活的日子，都在未来开出温柔而明亮的花。',
    '愿你常有小欢喜，也有稳稳接住生活的底气。',
    '愿今天的好心情，成为明天更多幸运的开始。',
    '愿你所行皆坦途，所遇皆温暖，所想皆有回响。',
    '愿日子清澈明朗，所盼之事都在悄悄靠近。',
    '愿你保持热爱，奔赴山海，也被世界温柔以待。',
    '愿每一次出发都有意义，每一段旅程都有惊喜。',
    '愿你心有繁花，一路芳华，平凡的日子也闪闪发亮。',
    '愿生活偶尔有风雨，但更多时候是晴朗与欢喜。',
    '愿你的努力被看见，你的真心被珍惜，你的期待不落空。',
    '愿你有前进一寸的勇气，也有停下来欣赏风景的从容。',
    '愿所有美好如期而至，所有幸运不期而遇。',
    '愿你忙而有序，闲而有趣，心中始终留有一片晴空。',
    '愿平安常伴左右，喜乐长驻心间，岁岁皆是好时光。',
    '愿你一路遇见善意，也成为照亮别人生活的微光。',
    '愿你拥有选择的自由，也拥有把选择变好的能力。',
    '愿每个清晨都有期待，每个夜晚都能安心入梦。',
    '愿你走过的路都算数，经历的事终会化作礼物。',
    '愿生活给你的答案，比你想象中更温柔、更圆满。',
    '愿你不慌不忙，步履坚定，把日子过成自己喜欢的模样。',
    '愿你有爱可依，有梦可追，有值得期待的明天。',
    '愿所有微小的坚持，都在未来汇成闪耀的光。',
    '愿你所得皆所愿，所失亦无憾，心安便是归处。',
    '愿风吹来好消息，愿花开时恰逢你经过。',
    '愿你始终相信，美好的事情正在来的路上。',
    '愿岁月温柔以待，也愿你有力量温柔地对待自己。',
    '愿你笑容常在，运气常来，喜欢的一切都在身边。',
    '愿前路辽阔，万事可期，每一步都有新的风景。',
    '愿你心怀浪漫，也有面对生活的清醒与勇敢。',
    '愿所有付出都有回报，所有等待都有值得的结果。',
    '愿你不被匆忙催促，按照自己的节奏慢慢发光。',
    '愿你被理解、被尊重、被真诚地爱，也永远懂得爱自己。',
    '愿寻常日子有诗意，柴米油盐也藏着细碎的欢喜。',
    '愿好运与你不期而遇，快乐在每个转角等你。',
    '愿你历经山河，仍觉人间值得，依旧心怀热望。',
    '愿每一份善意都有回声，每一个愿望都有归期。',
    '愿你今天比昨天自在，明天比今天更接近幸福。',
    '愿生活有暖阳、有清风，也有恰到好处的惊喜。',
    '愿你心之所向，皆有方向；一路前行，常有花香。',
  ],
  en: [
    'May your days be bright, your heart be light, and your path feel truly your own.',
    'May every quiet effort bloom into something beautiful in its own time.',
    'May you find small joys often and the courage to welcome bigger dreams.',
    'May today’s good feeling become the beginning of many fortunate tomorrows.',
    'May the road ahead be kind, the people warm, and your hopes answered.',
    'May life feel clear and open, with good things gently finding their way to you.',
    'May you keep what you love close and meet the world with a brave, open heart.',
    'May every new beginning bring meaning, wonder, and a reason to smile.',
    'May ordinary days glow with moments that make you glad to be exactly where you are.',
    'May passing storms give way quickly to calm skies and happier hours.',
    'May your work be seen, your kindness valued, and your hopes fulfilled.',
    'May you have the courage to move forward and the wisdom to enjoy the view.',
    'May beautiful things arrive on time, and lucky moments find you unexpectedly.',
    'May your busy days feel purposeful and your quiet days feel wonderfully full.',
    'May peace walk beside you, joy live within you, and each year treat you well.',
    'May you meet kindness along the way and become a little light for someone else.',
    'May you have the freedom to choose and the strength to make each choice worthwhile.',
    'May every morning hold promise and every evening bring peaceful rest.',
    'May every road you have taken count, and every experience become a gift.',
    'May life’s answers be gentler and more wonderful than you imagined.',
    'May you move at your own pace, steady and unhurried, toward a life you love.',
    'May you have love to lean on, dreams to follow, and tomorrow to look forward to.',
    'May every small act of persistence gather into a light that cannot be missed.',
    'May what you gain bring joy, what you release bring peace, and your heart feel at home.',
    'May the wind carry good news and flowers bloom just as you pass by.',
    'May you always trust that something beautiful is already on its way.',
    'May time be gentle with you, and may you always be gentle with yourself.',
    'May your smile stay close, good fortune visit often, and favorite things surround you.',
    'May the road open wide before you, full of possibility and new scenery.',
    'May you keep your sense of wonder and meet life with clarity and courage.',
    'May every sincere effort be rewarded and every patient wait prove worthwhile.',
    'May you never be rushed out of your rhythm, and may you shine in your own time.',
    'May you be understood, respected, sincerely loved, and always remember to love yourself.',
    'May simple days hold poetry and everyday moments carry quiet delight.',
    'May good luck find you unexpectedly and happiness wait around every corner.',
    'May all you see remind you that life is still beautiful and worth believing in.',
    'May every kindness echo back and every heartfelt wish find its season.',
    'May today feel freer than yesterday, and tomorrow bring you closer to happiness.',
    'May your life hold warm sunlight, a soft breeze, and just the right surprises.',
    'May your heart know where it is going, and may flowers line the way.',
  ],
}
export function normalizePaymentBlessingLanguage(locale: string | null | undefined): PaymentBlessingLanguage {
  return String(locale || '').trim().toLowerCase().startsWith('zh') ? 'zh' : 'en'
}
export function randomPaymentBlessing(
  locale: string | null | undefined,
  random: () => number = Math.random,
): string {
  const blessings = PAYMENT_BLESSINGS[normalizePaymentBlessingLanguage(locale)]
  const randomValue = Math.min(Math.max(random(), 0), 0.999999999999)
  return blessings[Math.floor(randomValue * blessings.length)] ?? blessings[0]
}
